
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
spec:
  selector:
    matchLabels:
      app: learner-service
  replicas: 2
  template:
    metadata:
      labels:
        app: learner-service
    spec:
      containers:
        - name: learner-service
          image: learner-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080