#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: learner-service
#  labels:
#    app: learner-service
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: learner-service
#  template:
#    metadata:
#      labels:
#        app: learner-service
#    spec:
#      containers:
#        - name: learner-service
#          image: learnerservice:latest
#          ports:
#            - containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: learner-service
#spec:
#  selector:
#    app: learner-service
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
spec:
  selector:
    matchLabels:
      app: learner-service
  replicas: 2
  template:
    metadata:
      labels:
        app: learner-service
    spec:
      containers:
        - name: learner-service
          image: learnerservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080