name: learner-service ci/cd

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT}}
  CLUSTER_NAME: autopilot-cluster-1
  ZONE_NAME: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        
    - name: Building and Pushing learner-service
      run: mvn package dockerfile:push --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubect1-action@master
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
        CLUSTER_NAME: ${{ env.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1-c
      with:
        args: apply -f k8s/
